export const URLs = {
    base: 'http://192.168.0.3/PENWorldAPI/API/Profile/',

    Login: 'Login',
    // forgotPassword: 'Login',
    ResendOTP: 'ResendOTP',
    VerifyOTP: 'VerifyOTP',
    RegisterFirebaseToken: 'RegisterFirebaseToken',
    ChangePassword: 'ChangePassword',
    GetNotifications: 'GetNotifications',
    GetNews: 'GetNews',
    GetEvents: 'GetEvents',
    GetMyChapters: 'GetMyChapters',
    GetMeetings: 'GetMeetings',
    GetCities: 'GetCities',
    GetBusinessCategories: 'GetBusinessCategories',
    GetRequirements: 'GetRequirements',
    GetMyRequirements: 'GetMyRequirements',
    GetRequirementDetails: 'GetRequirementDetails',
    AddEditRequirement:'AddEditRequirement',
    CloseRequirement:'CloseRequirement',
    SearchMembers:'SearchMembers',
    InviteForChapter:'InviteForChapter',
}
